package GUI.Reclamation;

import Entity.User.UserSession;
import GUI.Accueil.Accueil;
import com.codename1.ui.Button;
import com.codename1.ui.Container;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.util.UIBuilder;
import Service.Reclamation.ReclamationService;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class reclamation {

     Form mainForm;
   

    public reclamation() {
        Button addRecBtn = new Button("Ajouter une reclamation");
         addRecBtn.getUnselectedStyle().setFgColor(5542241);
        Button listRecBtn = new Button("Mes reclamations");
        listRecBtn.getUnselectedStyle().setFgColor(5542241);
        Container mainContainer = new Container();
        mainContainer.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        mainContainer.add(addRecBtn);
        mainContainer.add(listRecBtn);
         mainForm=new Form();
        mainForm.setLayout(new BorderLayout());
        mainForm.add(BorderLayout.CENTER,mainContainer);
        addRecBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                AddReclamation addRecUi = new AddReclamation();
                addRecUi.show();
            }
        });
        listRecBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                 new ReclamationService().findAll(UserSession.getInstace("", "").getUserName());
            }
        });
        Accueil a = new Accueil();
         mainForm.getToolbar().addCommandToLeftBar("Back", null,d->{
                                 a.getF().showBack();});
        
        mainForm.show();
    }

    public Form getMainForm() {
        return mainForm;
    }

    public void setMainForm(Form mainForm) {
        this.mainForm = mainForm;
    }
    

}
